/* OtherModule.c generated by valac 0.24.0, the Vala compiler
 * generated from OtherModule.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>


#define TYPE_OTHER_MODULE (other_module_get_type ())
#define OTHER_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OTHER_MODULE, OtherModule))
#define OTHER_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_OTHER_MODULE, OtherModuleClass))
#define IS_OTHER_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OTHER_MODULE))
#define IS_OTHER_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_OTHER_MODULE))
#define OTHER_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_OTHER_MODULE, OtherModuleClass))

typedef struct _OtherModule OtherModule;
typedef struct _OtherModuleClass OtherModuleClass;
typedef struct _OtherModulePrivate OtherModulePrivate;
typedef struct _ParamSpecOtherModule ParamSpecOtherModule;

struct _OtherModule {
	GTypeInstance parent_instance;
	volatile int ref_count;
	OtherModulePrivate * priv;
};

struct _OtherModuleClass {
	GTypeClass parent_class;
	void (*finalize) (OtherModule *self);
};

struct _ParamSpecOtherModule {
	GParamSpec parent_instance;
};


static gpointer other_module_parent_class = NULL;

gpointer other_module_ref (gpointer instance);
void other_module_unref (gpointer instance);
GParamSpec* param_spec_other_module (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_other_module (GValue* value, gpointer v_object);
void value_take_other_module (GValue* value, gpointer v_object);
gpointer value_get_other_module (const GValue* value);
GType other_module_get_type (void) G_GNUC_CONST;
enum  {
	OTHER_MODULE_DUMMY_PROPERTY
};
OtherModule* other_module_new (void);
OtherModule* other_module_construct (GType object_type);
void other_module_do_it (OtherModule* self);
void this_will_blow_harder (void);
static void other_module_finalize (OtherModule* obj);


OtherModule* other_module_construct (GType object_type) {
	OtherModule* self = NULL;
#line 5 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	self = (OtherModule*) g_type_create_instance (object_type);
#line 5 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	return self;
#line 64 "OtherModule.c"
}


OtherModule* other_module_new (void) {
#line 5 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	return other_module_construct (TYPE_OTHER_MODULE);
#line 71 "OtherModule.c"
}


void other_module_do_it (OtherModule* self) {
#line 8 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	g_return_if_fail (self != NULL);
#line 10 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	this_will_blow_harder ();
#line 80 "OtherModule.c"
}


static void value_other_module_init (GValue* value) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	value->data[0].v_pointer = NULL;
#line 87 "OtherModule.c"
}


static void value_other_module_free_value (GValue* value) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	if (value->data[0].v_pointer) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		other_module_unref (value->data[0].v_pointer);
#line 96 "OtherModule.c"
	}
}


static void value_other_module_copy_value (const GValue* src_value, GValue* dest_value) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	if (src_value->data[0].v_pointer) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		dest_value->data[0].v_pointer = other_module_ref (src_value->data[0].v_pointer);
#line 106 "OtherModule.c"
	} else {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		dest_value->data[0].v_pointer = NULL;
#line 110 "OtherModule.c"
	}
}


static gpointer value_other_module_peek_pointer (const GValue* value) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	return value->data[0].v_pointer;
#line 118 "OtherModule.c"
}


static gchar* value_other_module_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	if (collect_values[0].v_pointer) {
#line 125 "OtherModule.c"
		OtherModule* object;
		object = collect_values[0].v_pointer;
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		if (object->parent_instance.g_class == NULL) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 132 "OtherModule.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 136 "OtherModule.c"
		}
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		value->data[0].v_pointer = other_module_ref (object);
#line 140 "OtherModule.c"
	} else {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		value->data[0].v_pointer = NULL;
#line 144 "OtherModule.c"
	}
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	return NULL;
#line 148 "OtherModule.c"
}


static gchar* value_other_module_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	OtherModule** object_p;
	object_p = collect_values[0].v_pointer;
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	if (!object_p) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 159 "OtherModule.c"
	}
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	if (!value->data[0].v_pointer) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		*object_p = NULL;
#line 165 "OtherModule.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		*object_p = value->data[0].v_pointer;
#line 169 "OtherModule.c"
	} else {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		*object_p = other_module_ref (value->data[0].v_pointer);
#line 173 "OtherModule.c"
	}
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	return NULL;
#line 177 "OtherModule.c"
}


GParamSpec* param_spec_other_module (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecOtherModule* spec;
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_OTHER_MODULE), NULL);
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	return G_PARAM_SPEC (spec);
#line 191 "OtherModule.c"
}


gpointer value_get_other_module (const GValue* value) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_OTHER_MODULE), NULL);
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	return value->data[0].v_pointer;
#line 200 "OtherModule.c"
}


void value_set_other_module (GValue* value, gpointer v_object) {
	OtherModule* old;
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_OTHER_MODULE));
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	old = value->data[0].v_pointer;
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	if (v_object) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_OTHER_MODULE));
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		value->data[0].v_pointer = v_object;
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		other_module_ref (value->data[0].v_pointer);
#line 220 "OtherModule.c"
	} else {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		value->data[0].v_pointer = NULL;
#line 224 "OtherModule.c"
	}
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	if (old) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		other_module_unref (old);
#line 230 "OtherModule.c"
	}
}


void value_take_other_module (GValue* value, gpointer v_object) {
	OtherModule* old;
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_OTHER_MODULE));
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	old = value->data[0].v_pointer;
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	if (v_object) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_OTHER_MODULE));
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		value->data[0].v_pointer = v_object;
#line 249 "OtherModule.c"
	} else {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		value->data[0].v_pointer = NULL;
#line 253 "OtherModule.c"
	}
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	if (old) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		other_module_unref (old);
#line 259 "OtherModule.c"
	}
}


static void other_module_class_init (OtherModuleClass * klass) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	other_module_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	OTHER_MODULE_CLASS (klass)->finalize = other_module_finalize;
#line 269 "OtherModule.c"
}


static void other_module_instance_init (OtherModule * self) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	self->ref_count = 1;
#line 276 "OtherModule.c"
}


static void other_module_finalize (OtherModule* obj) {
	OtherModule * self;
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_OTHER_MODULE, OtherModule);
#line 284 "OtherModule.c"
}


GType other_module_get_type (void) {
	static volatile gsize other_module_type_id__volatile = 0;
	if (g_once_init_enter (&other_module_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_other_module_init, value_other_module_free_value, value_other_module_copy_value, value_other_module_peek_pointer, "p", value_other_module_collect_value, "p", value_other_module_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (OtherModuleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) other_module_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OtherModule), 0, (GInstanceInitFunc) other_module_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType other_module_type_id;
		other_module_type_id = g_type_register_fundamental (g_type_fundamental_next (), "OtherModule", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&other_module_type_id__volatile, other_module_type_id);
	}
	return other_module_type_id__volatile;
}


gpointer other_module_ref (gpointer instance) {
	OtherModule* self;
	self = instance;
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	g_atomic_int_inc (&self->ref_count);
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	return instance;
#line 309 "OtherModule.c"
}


void other_module_unref (gpointer instance) {
	OtherModule* self;
	self = instance;
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		OTHER_MODULE_GET_CLASS (self)->finalize (self);
#line 3 "/home/cran/Projects/noise/noise-perf-instant-search/tests/errors/module/OtherModule.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 322 "OtherModule.c"
	}
}



